FROM eddelbuettel/r2u:focal

LABEL maintainer="Peter Solymos <peter@analythium.io>"

RUN install.r shiny forecast jsonlite ggplot2 htmltools plotly

RUN addgroup --system app && adduser --system --ingroup app app
WORKDIR /home/app
COPY app .
RUN chown app:app -R /home/app
USER app

EXPOSE 3838

CMD ["R", "-e", "shiny::runApp('/home/app', port = 3838, host = '0.0.0.0')"]
